//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockchainExample.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blockchain
    {
        public int Index { get; set; }
        public string Data { get; set; }
        public string Hash { get; set; }
        public string PrevHash { get; set; }
        public long TimeStamp { get; set; }
        public int Nonce { get; set; }
    }
}
